name: Python application

on: pull_request
env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
  POSTGRES_DB_UNIVERSITY: ${{ secrets.POSTGRES_DB_UNIVERSITY }}
  AUTH_SERVICE_INTERNAL_URL: ${{ secrets.AUTH_SERVICE_INTERNAL_URL }}
  AUTH_SERVICE_API_URL: ${{ secrets.AUTH_SERVICE_API_URL }}
  UNIVERSITY_SERVICE_INTERNAL_URL: ${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
  UNIVERSITY_SERVICE_API_URL: ${{ secrets.UNIVERSITY_SERVICE_API_URL }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  network_run:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r requirments.txt
          
      - name: Run Docker Compose
        run: docker compose up -d

      - name: Pull Docker rep
        run: docker pull niklevchenko/api-tests:v2
      - name: Run test
        run: |
          mkdir my_vol
          docker run --network host niklevchenko/api-tests:v1
      - name: get dir
        run: |
          cd my_vol
          mkdir my_dir
          ls

