# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: workflow_dispatch
env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
  POSTGRES_DB_UNIVERSITY: ${ {secrets.POSTGRES_DB_UNIVERSITY }}
  AUTH_SERVICE_INTERNAL_URL: ${{ secrets.AUTH_SERVICE_INTERNAL_URL }} 
  AUTH_SERVICE_API_URL: ${{ secrets.AUTH_SERVICE_API_URL }}
  UNIVERSITY_SERVICE_INTERNAL_URL: ${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
  UNIVERSITY_SERVICE_API_URL: ${{ secrets.UNIVERSITY_SERVICE_API_URL }}
permissions:
  contents: read

jobs:
  network_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
      - name: Print docker
        run: docker version
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r requirments.txt
      - name: Run Docker Compose
        run: 
          docker compose up
  tests_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sleep for 30 seconds
        run: sleep 55s
        shell: bash
      - name: Pull Docker rep
        run: |
          docker pull niklevchenko/api-tests:v1
          docker run --network host niklevchenko/api-tests:v1
      
